from typing import Protocol, runtime_checkable

@runtime_checkable
class LoggerPort(Protocol):
    def info(self, message: str) -> None: ...
    def warn(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
