from typing import Protocol, runtime_checkable

@runtime_checkable
class DomainConfigPort(Protocol):
    # structure variables
    @property
    def window_size(self) -> int: ...
    # purchase variables
    @property
    def discount_z_score_threshold(self) -> float: ...
    @property
    def euphoria_z_score_threshold(self) -> float: ...
    @property
    def positive_trend_ma_threshold(self) -> float: ...
    # sale variables
    # -- at a profit
    @property
    def take_profit_price_constant_k(self) -> float: ...
    # -- at a loss
    @property
    def stop_price_constant_k(self) -> float: ...
    @property
    def stop_z_score(self) -> float: ...
    @property
    def stop_low_z_score_count(self) -> int: ...
    @property
    def stop_low_z_score_n(self) -> int: ...
    @property
    def stop_low_z_score_value(self) -> float: ...
